### ISSUE TITLE
Bug for fle/flt/feq ???

### ISSUE THREAD

**Issue by IC-Dream** [pulp-platform/riscv#52]
Hi,

From the riscv_spec_v2.2 Page 52:
![fcmp](https://user-images.githubusercontent.com/39543344/48816473-49d21600-ed7d-11e8-9326-e706403e33f0.PNG)

I created a directed case that set the operand to NAN like the below, but i didn't see that the NV flag was set  in RTL.
![ass](https://user-images.githubusercontent.com/39543344/48822549-70517a80-ed98-11e8-9748-a4ad5fa9f85a.PNG)

Thanks
Dream

**Comment by IC-Dream** [comment]
The fmin.s/fmax.s also exist the same issue. thanks.

**Comment by stmach** [comment]
Hello, I was just recently assigned.

Given the age of this issue, you're referencing a bug in the old FPU (https://github.com/pulp-platform/fpu). Since we're moving to a new FPU (https://github.com/pulp-platform/fpnew) which is used in the current and future releases of our cores, we are no longer updating the old FPU.
